id: P010774
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16928
  title: ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    4a9e0da5f0b14c3b98f46a6015e1e1e2:
      image_group_id: I1KG17096
      title: ''
      volume_number: 1
      total_pages: 276
